---
title: "Codigo Capitulo 1"
author: "Vicente Arce"
date: "`r Sys.Date()`"
output: html_document
---

# 1.3.2 Importación de paquetes
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if(!require(dplyr)) install.packages("dplyr")
if(!require(tidyr)) install.packages("tidyr")
if(!require(ggplot2)) install.packages("ggplot2")
if(!require(knitr)) install.packages("knitr")
if(!require(kableExtra)) install.packages("kableExtra")
```

```{=html}
<style>
body {
text-align: justify}
</style>
```

# 1.3.1 Importación de datos
```{r 1.3.1}
# Conjunto mtcars disponible en R
datos1 <- mtcars

# Importar archivo
datos2 <- read.csv("servidorescsv.csv")

# Mostrar las primeras 6 filas 
df2 <- data.frame(
  "Nombre" = datos2$Nombre,
  "Sistema Operativo" = datos2$SistemaOperativo,
  "Memoria Ram" = datos2$MemoriaRAM
)

head(df2) %>% 
   kbl(caption = "Tabla 1.") %>%
   kable_classic_2(full_width = T, html_font = "Cambria", bootstrap_options = "striped")

```


# 1.3.3 COnstrucción matriz de datos
```{r 1.3.3}
nombre <- c("nombre1", "nombre2", "nombre3")

fecha_nacimiento <- as.Date(c("2004-3-30", "2005-9-9", "2000-12-9"))

pep1 <- c(7.0, 6.5, 6.0)
pep2 <- c(6.5, 6.0, 6.0)

# Construyo el df
df <- data.frame(nombre, fecha_nacimiento, pep1, pep2, stringsAsFactors = FALSE)

# Guardar en CSV
write.csv2(df, "df.csv", row.names = FALSE)

```

# 1.3.4 Modificación de una matriz de datos

```{r 1.3.4.1}
df <- read.csv2("df.csv")

# Eliminar columna
df$fecha_nacimiento <- NULL

# Agrego la columna edad
df$edad <- c(20, 19, 23)

# Creo un a nueva observación
nuevaobs <- data.frame(nombre = "nombre4",
                    pep1 = 5.0,
                    pep2 = 3.8,
                    edad = 27)

# Agregar la nueva observación al df
df <-rbind(df, nuevaobs)

# Elimino las primeras 2 obs
df <- df[-c(1:3),]

# Guardo el df en un csv
write.csv2(df, "df2.csv")
```

```{r 1.3.4.2}
# Transformaciones más complejas con las siguietes funciones 
datos <-iris
# Filter(): Selecciona filas de acuerdo al valor contenido en una o más variables
largas <- datos %>% filter(Species == "versicolor", Sepal.Length >= 6)

# Select(): Permite seleccionar variables por sus nombre
petalos <- datos %>% select(Species, starts_with("Petal"))

# Mutate(): Permite modificar algunas variables o agregar nuevas
petalos <- petalos %>% mutate(Species, Petal.Width, Petal.Ratio = Petal.Length/Petal.Width)

# Arrange(): Modifica el orden de las filas
petalos <- petalos %>% arrange(desc(Petal.Ratio))



Instancia <- 1:6
Quicksort <- c(23.2, 22.6, 23.4, 23.3, 21.8, 23.9)
Bubblesort <- c(31.6, 29.3, 30.7, 30.8, 29.8, 30.3)
Radixsort <- c(30.1, 28.4, 28.7, 28.3, 29.9, 29.1)
Mergesort <- c(25.0, 25.7, 25.7, 23.7, 25.5, 24.7)
datos <- data.frame(Instancia, Quicksort, Bubblesort, Radixsort, Mergesort)

head(datos) %>% 
  kbl(caption = "Tabla 2.1.") %>%
   kable_classic_2(full_width = T, html_font = "Cambria", bootstrap_options = "striped")
# Pivot_longer(cols, names_to, values_to)
datos_largos <- datos %>% pivot_longer(c("Quicksort", "Bubblesort", "Radixsort", "Mergesort"), names_to = "Algortimo", values_to = "Tiempo")

# Muestro las primeras filas
head(datos_largos) %>% 
   kbl(caption = "Tabla 2.2.") %>%
   kable_classic_2(full_width = T, html_font = "Cambria", bootstrap_options = "striped")

# pivot_wider(names_from, values_from)
datos_anchos <- datos_largos %>% pivot_wider(names_from = "Algortimo", values_from = "Tiempo")

```

```{r 1.3.4.2}
# Funcion rename y factor(x, levels, labels, ordered)
datos_mtcars <- mtcars

# rename
datos_mtcars <- datos_mtcars %>% rename(Rendimiento = mpg, Cilindrada = cyl, Desplazamiento = disp, Potencia = hp, Eje = drat, Peso = wt, Cuarto_milla = qsec, Motor = vs, Transmision = am, Cambios = gear, Carburadores = carb)

# factor
# Dar formato ordinal a las variables Cilindrada renombrando sus niveles .
datos_mtcars[["Cilindrada"]] <- factor(datos_mtcars[["Cilindrada"]], levels = c(4, 6, 8), labels = c("4 cilindros", "6 cilindros", "8 cilindros"), ordered = TRUE )

datos_mtcars[["Cambios"]] <- factor(datos_mtcars[["Cambios"]], levels = c(3, 4, 5), labels = c("3 cambios", "4 cambios", "5 cambios"), ordered = TRUE) 
# Mostrar primeras 
head(datos_mtcars) %>% 
   kbl(caption = "Tabla 2.1.") %>%
   kable_classic_2(full_width = T, html_font = "Cambria", bootstrap_options = "striped")

# write mtcars
write.csv2(datos_mtcars, "mtcars2.csv")
```





