---
title: "EP01"
author: "Vicente Arce, Benjamin Zúñiga"
date: "`r Sys.Date()`"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if(!require(dplyr)) install.packages("dplyr")
if(!require(tidyr)) install.packages("tidyr")
if(!require(ggplot2)) install.packages("ggplot2")
if(!require(dplyr)) install.packages("dplyr")
if(!require(ggpubr)) install.packages("ggpubr")
if(!require(ggplot2)) install.packages("ggplot2")
if(!require(ggmosaic)) install.packages("ggmosaic")
if(!require(kableExtra)) isntall.packages("kableExtra")
```


```{=html}
<style>
body {
text-align: justify}
</style>
```


```{r a }
# recojo los datos desde el csv en formato español
datos <- read.csv2("EP01 Datos Casen 2017.csv")


head(datos) %>% kbl(caption = "Tabla 1. Datos") %>% kable_classic_2(full_width = T, html_font = "Cambria", bootstrap_options = "striped")

```


### Pregunta Equipo 9: El nivel de ingreso de las mujeres de la RM ¿varía con el estado civil?

Las variables relevantes para responder las preguntas son:

```{r b}
variables <- data.frame(
  "Variable" = c("sexo", "ecivil", "ytot"),
  "Descripción" = c("Representa el sexo de las persona", "Representa el estado civil de las personas","Representa el ingreso total de las personas"),
  "Tipo de variable" = c("Variable categórica nominales dicotómica", "Variable categórica nominal politómica", "Variable numérica discreta ratio")
)

variables %>% kbl(caption = "Tabla 1. Variables relevantes") %>% kable_classic_2(full_width = T, html_font = "Cambria", bootstrap_options = "striped")



```



```{r c}
# Obtengo unicamente los datos que corresponden a las mujeres, con su estado civil y ingreso total correspondiente
datosM_ecivil_ytot <- datos %>% filter(sexo == "Mujer")  

# Renombro los estados civiles
# Se renombran los estados civiles
datosM_ecivil_ytot [["ecivil"]] <- factor(datosM_ecivil_ytot [["ecivil"]], levels = c("Casado(a)","Viudo(a)", "Soltero(a)", "Separado(a)","Conviviente o pareja sin acuerdo de unión civil", "Divorciado (a)", "Conviviente civil (con acuerdo de unión civil)", "Anulado(a)"), labels = c("Casada", "Viuda", "Soltera", "Separada", "Conviviente sin union civil", "Divorciada", "Conviviente civil", "Anulada"))

# Creo el resumen de los datos estadisticos de los salarios segun estado civil
resumen <- group_by(datosM_ecivil_ytot, ecivil) %>% 
  summarise(count = n(), mean(ytot), median(ytot), sd(ytot), IQR(ytot))

resumen <- data.frame(
  "Estado civil" = levels(datosM_ecivil_ytot$ecivil),
  "Cantidad" = resumen$`count`,
  "Promedio" = resumen$`mean(ytot)`,
  "Mediana" = resumen$`median(ytot)`,
  "Desviación Estandar" = resumen$`sd(ytot)`,
  "IQR" = resumen$`IQR(ytot)`
)

resumen %>% kbl(caption = "Tabla 2. Estadisticos de ingresos de mujeres según estado civil") %>% kable_classic_2(full_width = T, html_font = "Cambria", bootstrap_options = "striped")

# Creo el boxplot de el estado civil vs salario
g <- ggboxplot(datosM_ecivil_ytot, x = "ecivil",
               y = "ytot",
               pallete = "Viridis",
               fill = "ecivil",
               title = "Ingresos según estado civil",
               xlab = "estado civil",
               ylab = "Ingresos") + ylim(0,2700000)

print(g)
```

- Haciendo un analisis descriptivo, se puede decir que si existe una diferencia de ingreso según el estado civil.
